import Head from "next/head";
import { Inter } from "next/font/google";
import Testimonials from "@/Components/Testimonials/Testimonials";
import Hero from "@/Components/Hero/Hero";
import Socials from "@/Components/Socials/Socials";
import Map from "@/Components/Map/Map";
import Three from "@/Components/Three/Three";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Three />
        <Socials />
        <Testimonials />
        <Map />
      </main>
    </>
  );
}
